module.exports = {
	COMPLETED_WITHOUT_FAILING_TESTS:    0,
	COMPLETED_WITH_FAILING_TESTS:       2,
	NOT_COMPLETED_WITH_FAILING_TESTS:   3,
	APPLICATION_STOPPED_WITH_NO_ERRORS: 0,
	ERROR_DURING_APPLICATION_START:     1,
}
